//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVInput.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDV_Vendors
    {
        public string Company_Name { get; set; }
        public string Approval_Status { get; set; }
        public string Authorized_Checklist { get; set; }
        public string Vendor_No { get; set; }
        public string Products { get; set; }
        public string Notes { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Info { get; set; }
        public string Contact_E_Mail { get; set; }
    }
}
